language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm install -g codecov
after_script:
  - nyc report --reporter=text-lcov > coverage.lcov && codecov