name: Tests

on: [push, pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*']
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          npm ci
          npm install -g codecov
      - name: Build
        run: npm run build
      - name: Unit test
        run: npm t
      - name: Upload coverage
        uses: codecov/codecov-action@v2
